import json
from manim import *

# Load AI-generated blueprint
with open("../ai_pipeline/blueprint.json", "r") as f:
    blueprint = json.load(f)

# Load manual style configuration
with open("../docs/style_config.json", "r") as f:
    style = json.load(f)


class AutoGeneratedVideo(Scene):
    def construct(self):

        for scene in blueprint:
            visuals = []
            narration = scene["narration"]
            duration = scene["duration"]
            elements = scene["elements"]

            # Text
            text = Text(narration, font_size=28)
            if style["text_animation"] == "write":
                self.play(Write(text))
            else:
                self.play(FadeIn(text))
            visuals.append(text)

            # Boxes
            if "boxes" in elements and style["use_boxes"]:
                client = Rectangle(width=2, height=1).shift(LEFT * 3)
                server1 = Rectangle(width=2, height=1).shift(RIGHT * 3 + UP)
                server2 = Rectangle(width=2, height=1).shift(RIGHT * 3 + DOWN)
                self.play(Create(client))
                self.play(Create(server1), Create(server2))
                visuals.extend([client, server1, server2])

            # Arrows
            if "arrows" in elements and style["use_arrows"]:
                arrow1 = Arrow(client.get_right(), server1.get_left())
                arrow2 = Arrow(client.get_right(), server2.get_left())
                self.play(Create(arrow1), Create(arrow2))
                visuals.extend([arrow1, arrow2])

            self.wait(duration)

            # Transition
            if style["transition"] == "fade":
                self.play(*[FadeOut(v) for v in visuals])
            else:
                self.clear()
